apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}-service
  labels:
    app: {{ .Values.server.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    role: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.httpPort }}
      targetPort: 8153
      protocol: TCP
      name: http

    - port: {{ .Values.server.service.httpsPort }}
      targetPort: 8154
      protocol: TCP
      name: https
  selector:
    app: {{ .Values.server.name }}
    role: server
